"""empty message

Revision ID: 616bd7d182c1
Revises: 5f70eb3108ec
Create Date: 2023-11-14 19:25:39.686082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '616bd7d182c1'
down_revision = '5f70eb3108ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='4096 = admin | 128 = guest',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='4096 = admin | 128 = guest',
               existing_nullable=True)

    # ### end Alembic commands ###
