"""updated sales statistics model and added foreign key constraints to trade data model

Revision ID: eab1444ac7df
Revises: 735c324b3146
Create Date: 2023-11-14 07:33:30.534345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eab1444ac7df'
down_revision = '735c324b3146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_sales', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sales_volume', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('market_share', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['location_id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'])
        batch_op.drop_column('stat_series_name')
        batch_op.drop_column('stat_value')

    with op.batch_alter_table('trade_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['location_id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sales_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stat_series_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('market_share')
        batch_op.drop_column('sales_volume')
        batch_op.drop_column('average_price')
        batch_op.drop_column('total_sales')
        batch_op.drop_column('location_id')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
